### ISSUE TITLE
Default configuration not ideal

### ISSUE THREAD

**Issue by terrencebarr** [twilio/programmable-asset-tracker#1]
`default-cfg.json` defines settings that are not ideal, for example drain the battery quickly or lead to unexpected location results. Example:
- `"connectingPeriod": 180.0` will connect every 180s, regardless of the status of the device
- `"alwaysOn": false` will not update the position unless the device detects motion

Suggestion is to update `default-cfg.json` to ensure expected device behavior

**Comment by alexey-nbl** [comment]
I also suggest to rename default-cfg to example-cfg.
To avoid confusion.
This example has no any relation to the default configuration.
Default configuration is set by the DEFAULT_CFG env variable (as specified in the readme).

**Comment by terrencebarr** [comment]
Good point, will do
